### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by kvark** [bryal/d3d11-rs#3]
Any chance of getting the library published on crates.io?

**Comment by bryal** [comment]
This library can be found on crates.io under the name [d3d11-win](https://crates.io/crates/d3d11-win/).
I suggest, however, that you use the winapi crate instead, if possible. I am not maintaining this lib very actively.

**Comment by kvark** [comment]
FYI, you library is the only way to go whenever somebody needs `D3DReflect` calls. These are rather mandatory for anything more than a simple demo.

Also, please consider having a crates.io badge in the readme.

**Comment by bryal** [comment]
I did not know that, thank you.

I just added a crates.io badge and link to doc as well.
