### ISSUE TITLE
about fixed-array, this library ffi rule is wrong.

### ISSUE THREAD

**Issue by llcxiongmao** [bryal/d3d11-rs#4]
example:
ClearRenderTargetView should be: 
unsafe fn ClearRenderTargetView(&mut self, pRenderTargetView: *mut ID3D11RenderTargetView, ColorRGBA: &[FLOAT; 4])
instead of:
unsafe fn ClearRenderTargetView(&mut self, pRenderTargetView: *mut ID3D11RenderTargetView, ColorRGBA: [FLOAT; 4])

c language fix array is pass by reference(or pointer) instead of value.

**Comment by bryal** [comment]
I'm not actively maintaing this repo anymore.
Check out https://crates.io/crates/d3d11-sys, https://github.com/retep998/winapi-rs, for an actively updated project with more extensive coverage of the d3d11 API
